### ISSUE TITLE
Errors are reporting as Warnings

### ISSUE THREAD

**Issue by jeffbeckncbi** [JATS4R/jats-validator#11]
The tests that I did get to report are assigning ERROR as WARNING. Do I need to separate those in the jats4r.sch again? I may have oversimplified things  - relying on the ERROR/WARNING indicator in the messages (that we removed). 

Specifically when country/@country is not a 2-letter string or the attribute is not included. 

I will add test files for this and other tests (errors and warnings) that we can use going forward. I'll put these in jats-schematrons/samples

**Comment by hubgit** [comment]
`schematron-runner` is expecting that the tests will be separated into `errors` and `warnings` phases, like [this](https://github.com/TimLuq/schematron-runner/blob/b7686c1efb1c3a1bebce698c162b111e112cb334/test/fixtures/test-1.sch#L4-L12), as they were previously.

**Comment by jeffbeckncbi** [comment]
I'll put those back :)

**Comment by jeffbeckncbi** [comment]
phases added back in fourth-update, branch merged
