### ISSUE TITLE
Validator not working

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/jats-validator#32]
<img width="1384" alt="Screenshot 2022-10-01 at 08 48 30" src="https://user-images.githubusercontent.com/6051876/193399087-322c231a-9ed9-4f0a-8e78-d77b99c307a4.png">

Hi there

I have received feedback from a user that the service is not working and I tested it, see screenshot of the response I received.

Is there a problem with the code that you can fix?

Thanks!

Melissa

**Comment by hubgit** [comment]
I just tried with [one article XML](https://peerj.com/articles/1000.xml) and it finished successfully. Are you able to share any of the article XML files that are failing?

**Comment by castedo** [comment]
Here's a JATS XML file that I see failing:
https://archive.softwareheritage.org/browse/content/sha1_git:e3674cd3cd1e422aac79bf43492dada47198a0b8/raw/

**Comment by hubgit** [comment]
It seems that for some reason the catalog resolution isn't working properly, as validating the example file succeeds if I change `JATS-archivearticle1.dtd` to `http://jats.nlm.nih.gov/archiving/1.2/JATS-archivearticle1.dtd`

It might take a while to work out why Saxon isn't using the public ID (`-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2 20190208//EN`) to find the DTD file locally.

**Comment by castedo** [comment]
Thanks for looking into it!

@hubgit What's the relationship between 

* https://jats-validator.vercel.app/
* https://jats-validator.hubmed.org/ and
* https://validator.jats4r.org/ ?

To be honest, I probably prefer to use an OCI container image like
https://github.com/JATS4R/jats-validator-docker
but that just takes the XML as stdin, takes a few command line options and then spits out a report to stdout.

Has anybody built such a container image?

**Comment by hubgit** [comment]
The issue with catalog resolution was [reported upstream](https://saxonica.plan.io/issues/5704) and a fix was released in SaxonC 12.0.

**Comment by hubgit** [comment]
The validator is now updated to SaxonC 12.1, so this issue should be fixed.

**Comment by castedo** [comment]
Thank you!

I just tried it out with some newly generated JATS XML and it appears to be working great.
