### ISSUE TITLE
Does not recognise DTD: JATS-archivearticle1-mathml3.dtd

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/jats-validator#8]
![Screenshot 2019-05-15 at 12 53 54](https://user-images.githubusercontent.com/6051876/57773901-04314d00-7711-11e9-99ab-a349325a56a7.png)

@hubgit

**Comment by hubgit** [comment]
@Melissa37 Could you show the doctype from the start of the XML (or attach the whole XML file)?

**Comment by Melissa37** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2 20151215//EN" "JATS-archivearticle1-mathml3.dtd">
<article article-type="research-article" dtd-version="1.2"
    xmlns:ali="http://www.niso.org/schemas/ali/1.0/" xmlns:mml="http://www.w3.org/1998/Math/MathML"
    xmlns:xlink="http://www.w3.org/1999/xlink">
```

Github does not support uploading XML files. I can send it to you via email if that helps?

**Comment by hubgit** [comment]
That's plenty, thanks :)

The problem is that the publicID in the XML file's doctype is incorrect - it should be 

```
-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2 20190208//EN
```

rather than 

```
-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2 20151215//EN
```

We can probably do something to check the public ID against the list of supported DTDs before attempting validation.

**Comment by Melissa37** [comment]
Fab, thanks for letting me know, I tried with updated and it worked. Now got to fix our production files :-(

**Comment by hubgit** [comment]
I've created #9 for checking the public ID and returning a useful error message if it's not supported.
